steps:
  - name: 'python:3.10-slim'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install dependencies
        pip install -r requirements.txt

        # Run tests or other commands (optional)
        # ...

        # Build the Docker image
        docker build -t gcr.io/$PROJECT_ID/flask-app .

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flask-app'

images:
  - 'gcr.io/$PROJECT_ID/flask-app'