steps:
  - name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python -m gunicorn -b :$PORT main:app

images:
  - 'gcr.io/$PROJECT_ID/flask-app'

deploy:
  name: 'gcr.io/$PROJECT_ID/flask-app'
  region: 'us-central1'
