steps:
  - name: 'gcr.io/buildpacks/builder'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Build the application using buildpacks
        pack build my-flask-app --builder gcr.io/buildpacks/builder:v1

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy the application to Google Cloud Run
        gcloud run deploy my-flask-app \
          --image gcr.io/$PROJECT_ID/my-flask-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated