steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strava-gemini'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/strava-gemini'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy the application to Google Cloud Run
        gcloud run deploy strava-gemini \
          --image gcr.io/$PROJECT_ID/strava-gemini \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
